version: '2'

services:
  hub:
    build: hub/.
    ports:
     - "4433:4433"
    image: selenium_grid/hub:2.53.1
    logging:
      driver: "json-file"
    network_mode: "host"
    volumes:
      - ./logs:/var/log
    environment:
      JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom"

  firefox:
    build: firefox/.
    image: selenium_grid/firefox:45.3.0esr
    links:
     - hub
    expose:
     - "5555"
    logging:
      driver: "json-file"
    volumes:
      - ./logs:/var/log
    environment:
      JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom"

