version: '2'

services:
  hub:
    container_name: selenium-hub
    image: selenium/hub:3.5.3
    ports:
     - "4433:4444"

  chrome:
    image: selenium/node-chrome:3.5.3
    environment:
     - HUB_PORT_4444_TCP_ADDR=hub
     - HUB_PORT_4444_TCP_PORT=4444
    expose:
     - "5555"

  firefox:
    image: selenium/node-firefox:3.5.3
    environment:
     - HUB_PORT_4444_TCP_ADDR=hub
     - HUB_PORT_4444_TCP_PORT=4444
    expose:
     - "5555"

  jenkins:
    build: jenkins/.
    image: jenkins
    container_name: ncjenkins
    volumes:
     - ncjenkins_home:/var/jenkins_home
    links:
     - "hub:selenium-hub"
    ports:
     - "8080:8080"
     - "5000:5000"

volumes:
  ncjenkins_home:
    external: true

