version: '2'

services:
  hub:
    build: hub/.
    ports:
     - "4444:4444"
    image: selenium_grid/hub
    logging:
      driver: "json-file"
    network_mode: "host"
    volumes:
      - ./logs:/var/log

  firefox:
    build: firefox/.
    image: selenium_grid/firefox
    links:
     - hub
    expose:
     - "5555"
    logging:
      driver: "json-file"
    volumes:
      - ./logs:/var/log

  chrome:
    build: chrome/.
    image: selenium_grid/chrome
    links:
     - hub
    expose:
     - "5555"
    logging:
      driver: "json-file"
    volumes:
      - ./logs:/var/log

